name: Pull, Rebuild, and Run Preview

on:
  push:
    branches: [ main ]  # You can change this to specific branches or use '*' for all branches

jobs:
  pull-rebuild-preview:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetches all history for all branches and tags
    
    - name: Pull latest changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git pull origin ${GITHUB_REF#refs/heads/} --no-rebase
        git status
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Choose your preferred Node.js version
        cache: 'npm'  # Or 'yarn' if you use yarn
    
    - name: Install dependencies
      run: npm install  # Or 'yarn install'
    
    - name: Build with Vite
      run: npm run build  # Or 'yarn build', assuming this script uses Vite
    
    - name: Deploy to preview environment
      run: |
        
        npm run preview &  # Using npx serve as an example
        
        # Wait for server to start
        sleep 5
        
        echo "Preview deployed at: http://localhost:8085"
        echo "Preview available at: https://jwani-app.fairpiranha.box.ca/" # Replace with your actual preview domain
    
    - name: Save preview URL
      run: |
        echo "::set-output name=preview_url::https://jwani-app.fairpiranha.box.ca/"
      id: preview
    
    - name: Comment on commit with preview URL
      uses: peter-evans/commit-comment@v2
      with:
        body: |
          🚀 Preview deployment is ready!
          
          Preview URL: ${{ https://jwani-app.fairpiranha.box.ca/ }}
          
